import { Center, Flex, Text } from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import { useEffect, useState } from "react"
import CheckGroup from "../components/CheckGroup"
import formatContent from "../utils/formatContent"

const Home: NextPage = () => {
    const router = useRouter()
    const [content, setContent] = useState<{ [key: string]: string }>({})

    useEffect(() => {
        const data = localStorage.getItem("data")
        if (!data) router.replace("/upload")
        else setContent(formatContent(data))
    }, [])

    return (
        <Center minH="100vh">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Flex flexDirection="row" flexWrap="wrap">
                <CheckGroup names={Object.keys(content)} />
                <Text></Text>
            </Flex>
        </Center>
    )
}

export default Home
