import { Center } from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
    return (
        <Center>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </Center>
    )
}

export default Home
