import { Center, Button } from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"

const Upload: NextPage = () => {
    return (
        <Center minH="100vh">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <form method="POST" action="/api/process">
                <input type="file" accept=".txt" name="file" id="file"></input>
                <Button type="submit">Submit</Button>
            </form>
        </Center>
    )
}

export default Upload
