import { AttachmentIcon } from "@chakra-ui/icons"
import { Center, Button } from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import { useState, useRef, FormEvent } from "react"

const Upload: NextPage = () => {
    const router = useRouter()
    const [loading, setLoading] = useState(false)
    let fileRef = useRef<HTMLInputElement>()

    const readFile = (event: FormEvent<HTMLInputElement>) => {
        setLoading(true)
        const fileReader = new FileReader()
        //@ts-ignore
        const { files } = event.target

        fileReader.readAsText(files[0], "UTF-8")
        fileReader.onload = (e) => {
            const content = e.target!.result
            if (content) localStorage.setItem("data", content.toString())
            setLoading(false)
            router.push("/")
        }
    }

    return (
        <Center minH="100vh">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <input
                //@ts-ignore
                ref={fileRef}
                type="file"
                accept=".txt"
                onChange={readFile}
                style={{ display: "none" }}></input>
            <Button
                type="submit"
                onClick={() => {
                    fileRef.current!.click()
                }}
                leftIcon={<AttachmentIcon />}
                isLoading={loading}>
                Upload TXT file
            </Button>
        </Center>
    )
}

export default Upload
